// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20221208060906_UpdateDataTable")]
    partial class UpdateDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Server.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchId");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("Server.Models.Data", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"), 1L, 1);

                    b.Property<double>("PhiScrew")
                        .HasColumnType("float");

                    b.Property<int>("ScrewId")
                        .HasColumnType("int");

                    b.Property<double>("SensFx")
                        .HasColumnType("float");

                    b.Property<double>("SensFy")
                        .HasColumnType("float");

                    b.Property<double>("SensFz")
                        .HasColumnType("float");

                    b.Property<double>("SensTx")
                        .HasColumnType("float");

                    b.Property<double>("SensTy")
                        .HasColumnType("float");

                    b.Property<double>("SensTz")
                        .HasColumnType("float");

                    b.Property<double>("Ta7")
                        .HasColumnType("float");

                    b.Property<double>("TcpFx")
                        .HasColumnType("float");

                    b.Property<double>("TcpFy")
                        .HasColumnType("float");

                    b.Property<double>("TcpFz")
                        .HasColumnType("float");

                    b.Property<double>("TcpTx")
                        .HasColumnType("float");

                    b.Property<double>("TcpTy")
                        .HasColumnType("float");

                    b.Property<double>("TcpTz")
                        .HasColumnType("float");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("DataId");

                    b.HasIndex("ScrewId");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("Server.Models.Screw", b =>
                {
                    b.Property<int>("ScrewId")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ok")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("datetime2");

                    b.HasKey("ScrewId");

                    b.HasIndex("BatchId");

                    b.ToTable("Screw");
                });

            modelBuilder.Entity("Server.Models.Data", b =>
                {
                    b.HasOne("Server.Models.Screw", "Screw")
                        .WithOne("Data")
                        .HasForeignKey("Server.Models.Data", "ScrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screw");
                });

            modelBuilder.Entity("Server.Models.Screw", b =>
                {
                    b.HasOne("Server.Models.Batch", "Batch")
                        .WithMany("Screws")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Server.Models.Batch", b =>
                {
                    b.Navigation("Screws");
                });

            modelBuilder.Entity("Server.Models.Screw", b =>
                {
                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
